---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: tracee
    app.kubernetes.io/component: tracee
    app.kubernetes.io/part-of: tracee
  name: tracee-policies
  namespace: monitoring
data:
  signatures.yaml: |-
    name: signature_events
    description: traces all signature events
    defaultActions:
      - log
    scope:
      - global
    rules:
      - event: stdio_over_socket
      - event: k8s_api_connection
      - event: aslr_inspection
      - event: proc_mem_code_injection
      - event: docker_abuse
      - event: scheduled_task_mod
      - event: ld_preload
      - event: cgroup_notify_on_release
      - event: default_loader_mod
      - event: sudoers_modification
      - event: sched_debug_recon
      - event: system_request_key_mod
      - event: cgroup_release_agent
      - event: rcd_modification
      - event: core_pattern_modification
      - event: proc_kcore_read
      - event: proc_mem_access
      - event: hidden_file_created
      - event: anti_debugging
      - event: ptrace_code_injection
      - event: process_vm_write_inject
      - event: disk_mount
      - event: dynamic_code_loading
      - event: fileless_execution
      - event: illegitimate_shell
      - event: kernel_module_loading
      - event: k8s_cert_theft
      - event: proc_fops_hooking
      - event: syscall_hooking
      - event: dropped_executable
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: tracee
    app.kubernetes.io/component: tracee
    app.kubernetes.io/part-of: tracee
  name: tracee-config
  namespace: monitoring
data:
  config.yaml: |-
    cache:
      - cache-type=mem
      - mem-cache-size=512
    perf-buffer-size: 1024
    containers: true
    healthz: true
    metrics: true
    pprof: false
    pyroscope: false
    listen-addr: :3366
    log:
        - info
    output:
        - json
        - option:parse-arguments