---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: pls-dont-hack-me
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: ubuntu:22.04
        command: ["/bin/sleep", "infinity"]
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
      serviceAccountName: read-secrets
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: tracee
    app.kubernetes.io/component: tracee
    app.kubernetes.io/part-of: tracee
  name: tracee
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: tracee
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tracee
      name: tracee
    spec:
      containers:
      - name: tracee
        image: docker.io/aquasec/tracee:0.16.0
        imagePullPolicy: IfNotPresent
        command: 
          - /tracee/tracee
        args:
          - --policy
          - /tracee/policies
          - --config 
          - /tracee/config.yaml
        env:
          - name: LIBBPFGO_OSRELEASE_FILE
            value: /etc/os-release-host
        readinessProbe:
          httpGet:
            path: /healthz
            port: 3366
        securityContext:
          privileged: true
        volumeMounts:
        - name: tmp-tracee
          mountPath: /tmp/tracee
        - name: etc-os-release
          mountPath: /etc/os-release-host
          readOnly: true
        - mountPath: /var/run/containerd/containerd.sock
          name: containerd-sock
          readOnly: true
        - mountPath: /var/run/crio/crio.sock
          name: crio-sock
          readOnly: true
        - mountPath: /var/run/docker.sock
          name: docker-sock
          readOnly: true
        - mountPath: /var/run/podman/podman.sock
          name: podman-sock
          readOnly: true
        - name: tracee-config
          readOnly: true
          mountPath: /tracee/config.yaml
          subPath: config.yaml
        - name: tracee-policies
          readOnly: true
          mountPath: /tracee/policies
        # NOTE: Resource consumption will vary between different use cases and
        # workload characteristics. User should monitor tracee for resource
        # consumption before enabling resource limits. Capping tracee
        # resources may cause loss of events and miss detections. Golang
        # signatures outperforms REGO signatures, use less HW resources,
        # and are preferred if that is an option.
        # resources:
        resources:
          limits:
            cpu: "1"
            memory: 1Gi # tracee has a 512MB in-memory events cache enabled by default
          requests:
            cpu: "1"
            memory: 1Gi
      tolerations:
        - effect: NoSchedule
          operator: Exists
        - effect: NoExecute
          operator: Exists
      volumes:
      - hostPath:
          path: /tmp/tracee
        name: tmp-tracee
      - hostPath:
          path: /etc/os-release
        name: etc-os-release
      - hostPath:
          path: /var/run/containerd/containerd.sock
        name: containerd-sock
      - hostPath:
          path: /var/run/crio/crio.sock
        name: crio-sock
      - hostPath:
          path: /var/run/podman/podman.sock
        name: podman-sock
      - hostPath:
          path: /var/run/docker.sock
        name: docker-sock
      - name: tracee-config
        configMap:
          name: tracee-config
      - name: tracee-policies
        configMap:
          name: tracee-policies
