---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prometheus-ui
spec:
  ingressClassName: ngrok
  rules:
    - host: ${NGROK_SUBDOMAIN}.ngrok.io
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: prometheus-service
              port: 
                number: 8080