---
apiVersion: v1
kind: Namespace
metadata:
  name: pls-dont-hack-me
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: v1
kind: Namespace
metadata:
  name: ngrok-ingress