---
- hosts: localhost
  name: Setup Kubernetes cluster
  gather_facts: false
  tasks:
    - name: Get ngrok credentials
      ansible.builtin.include_vars:
        file: "{{ lookup('env', 'HOME') }}/.config/ngrok/ngrok.yml"
        # variable should be accessed as api_key and authtoken

    - name: Install ngrok ingress controller
      ansible.builtin.command:
        cmd: |
          helm install ngrok-ingress-controller 
          ngrok/kubernetes-ingress-controller 
          --set credentials.apiKey={{ api_key }} 
          --set credentials.authtoken={{ authtoken }}

    - name: Create namespaces
      ansible.builtin.command: kubectl apply -f k8s-manifests/namespaces.yaml
      register: kubectl_run
      changed_when:
        - "'created' in kubectl_run.stdout"

    - name: Create ClusterRoles
      ansible.builtin.command: kubectl apply -f k8s-manifests/clusterroles.yaml
      register: kubectl_run
      changed_when:
        - "'created' in kubectl_run.stdout"

    - name: Create Service Accounts
      ansible.builtin.command: kubectl apply -f k8s-manifests/serviceaccounts.yaml
      register: kubectl_run
      changed_when:
        - "'created' in kubectl_run.stdout"

    - name: Create ClusterRoleBindings
      ansible.builtin.command: kubectl apply -f k8s-manifests/clusterrolebindings.yaml
      register: kubectl_run
      changed_when:
        - "'created' in kubectl_run.stdout"

    - name: Create ConfigMaps
      ansible.builtin.command: kubectl apply -f k8s-manifests/configmaps.yaml
      register: kubectl_run
      changed_when:
        - "'created' in kubectl_run.stdout"

    - name: Create Deployments
      ansible.builtin.command: kubectl apply -f k8s-manifests/deployments.yaml
      register: kubectl_run
      changed_when:
        - "'created' in kubectl_run.stdout"

    - name: Create Services
      ansible.builtin.command: kubectl apply -f k8s-manifests/services.yaml
      register: kubectl_run
      changed_when:
        - "'created' in kubectl_run.stdout"

    - name: Create Ingress
      ansible.builtin.command: kubectl apply -f k8s-manifests/ingress.yaml
      environment: 
        NGROK_SUBDOMAIN: "{{ lookup ('env', 'USER') }}-dc31"
      register: kubectl_run
      changed_when:
        - "'created' in kubectl_run.stdout"