---
- hosts: localhost
  name: Setup localhost
  gather_facts: false
  tasks:
    - name: Install Docker and other dependencies
      ansible.builtin.apt:
        pkg:
          - docker.io
          - etcd-client
          - jq
          - unzip
      become: true
    - name: Add current user to Docker group
      ansible.builtin.user:
        name: "{{ lookup('env', 'USER') }}"
        groups: docker
        append: true
      become: true
    - name: Get latest stable kubectl version
      ansible.builtin.uri:
        url: https://dl.k8s.io/release/stable.txt
        return_content: yes
      register: kubectl_version
    - name: Download kubectl
      ansible.builtin.uri:
        url: "https://dl.k8s.io/release/{{ kubectl_version.content }}/bin/linux/amd64/kubectl"
    - name: Get file hash for kubectl
      ansible.builtin.uri:
        url: "https://dl.k8s.io/{{ kubectl_version.content }}/bin/linux/amd64/kubectl.sha256"
        return_content: yes
      register: kubectl_sha256
    - name: Compare hash values
      ansible.builtin.shell: echo "{{ kubectl_sha256.content }} kubectl" | sha256sum --check
      register: cmd_output
      failed_when:
        - "'OK' not in cmd_output.stdout"
    - name: Show download result
      ansible.builtin.debug:
        msg: "Download of {{ cmd_output.stdout }}"
    # - name: Create a namespace for privesc
    #   ansible.builtin.command: kubectl apply -f k8s-manifests/namespaces.yaml
    #   register: cmd_output
    #   changed_when:
    #     - "'created' in cmd_output.stdout"
    # - name: Create a ClusterRole and ClusterRoleBinding
    #   ansible.builtin.command: kubectl apply -f k8s-manifests/secrets-clusterrole.yaml
