---
- hosts: localhost
  gather_facts: no
  vars:
    sha256check:
      ok: "kubeectl:OK"
  tasks:
   - name: Add current user to Docker group
     command: sudo usermod -aG docker $USER
   - name: Download kubectl
     command: curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
   - name: Get file hash for kubectl
     command: curl -LO "https://dl.k8s.io/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl.sha256"
   - name: Compare hash values
     shell: echo "$(<kubectl.sha256) kubectl" | sha256sum --check
     register: command_output
   - name: Verify everything okay
     set_fact:
       hash_check_success: "{{ command_output.stdout == sha256check['ok'] }}"
   - name: 
       debug: 
         msg: "kubectl checks out okay"
       when: hash_check_success   
   - name: Create a namespace for privesc
     command: kubectl apply -f k8s-manifests/namespaces.yaml
   - name: Create a ClusterRole and ClusterRoleBinding
     command: kubectl apply -f k8s-manifests/secrets-clusterrole.yaml
