---
- hosts: localhost
  name: Setup Kubernetes cluster
  gather_facts: false
  tasks:
    - name: Create namespaces
      ansible.builtin.command: kubectl apply -f k8s-manifests/namespaces.yaml
      register: kubectl_run
      changed_when:
        - "'created' in kubectl_run.stdout"

    - name: Create ClusterRoles
      ansible.builtin.command: kubectl apply -f k8s-manifests/clusterroles.yaml
      register: kubectl_run
      changed_when:
        - "'created' in kubectl_run.stdout"

    - name: Create ClusterRoleBindings
      ansible.builtin.command: kubectl apply -f k8s-manifests/clusterrolebindings.yaml
      register: kubectl_run
      changed_when:
        - "'created' in kubectl_run.stdout"
