


    # - name: Create a namespace for privesc
    #   ansible.builtin.command: kubectl apply -f k8s-manifests/namespaces.yaml
    #   register: cmd_output
    #   changed_when:
    #     - "'created' in cmd_output.stdout"
    # - name: Create a ClusterRole and ClusterRoleBinding
    #   ansible.builtin.command: kubectl apply -f k8s-manifests/secrets-clusterrole.yaml